swagger: "2.0"
info:
  description: "API for my app"
  version: "1.0.0"
  title: "My App API"
host: "team2go-api.ru"
basePath: "/"
schemes:
  - "https"
paths:
  /user/{user_id}/list_of_activities:
    get:
      summary: "List of activities"
      parameters:
        - name: "user_id"
          in: "path"
          description: "ID of the user"
          required: true
          type: "integer"
      responses:
        200:
          description: "List of activities"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                type:
                  type: "string"
                scorecard:
                  type: "string"
                color:
                  type: "string"
                tag:
                  type: "string"

